### ISSUE TITLE
Stuck in infinite recursive loop

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#167]
**[Original report](https://bitbucket.org/ronaldoussoren/py2app/issue/167) by Elvin Lemmens (Bitbucket: [elvinlemmens](https://bitbucket.org/elvinlemmens), GitHub: [elvinlemmens](https://github.com/elvinlemmens)).**

----------------------------------------

I have issues when trying to generate an app.
The process failes with this message:

creating /Users/ilab/source/tickets/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build
creating /Users/ilab/source/tickets/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel
creating /Users/ilab/source/tickets/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone
creating /Users/ilab/source/tickets/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app
error: could not create '/Users/ilab/source/tickets/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app/collect/PR107188/build/bdist.macosx-10.6-intel/python2.7-standalone/app': File name too long

I can't see any symlink.
Hope there is an easy fix.
Elv

**Comment by kontur** [comment]
@ronaldoussoren If you see the mentioned issue you'll see it's not entirely the same error message, but looks very similar in that the bundle collection seems to recurse. Any pointers as to what to test further?

Also if you feel this is a different issue entirely I'm happy to open a new one.
