### ISSUE TITLE
New Mach-O header is too large to relocate in

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#219]
**[Original report](https://bitbucket.org/ronaldoussoren/py2app/issue/219) by Terrence Katzenbaer (Bitbucket: [pandabloc](https://bitbucket.org/pandabloc), ).**

----------------------------------------

Similar to Issue #93, except I installed `scipy` through `pip` instead of Macports. Do you have any advice on how I could resolve this issue?

Interestingly, this bug happens in two apps (one that uses `scipy` directly and one that doesn't use `scipy` but uses `numpy`) only in the `virtualenv` that has `scipy` pip-installed. If I switch to another `virtualenv` without `scipy` pip-installed, then it will work fine on the app that doesn't use `scipy` and break on missing a Fortran compiler on the app that does use `scipy`.

```
#!

ValueError: New Mach-O header is too large to relocate in '/Users/xxxxxxxxxxx/Developer/xxxxxxxxxxx/dist/xxxxxxxxxxxxxxxx.app/Contents/Resources/lib/python2.7/scipy/optimize/_nnls.so' (new size=1532L, max size=1504L, delta=108L)
```

**Comment by albertosottile** [comment]
@ronaldoussoren This just happened to me with `cryptography==38.0.3` (38.0.1 builds fine). 
```
ValueError: New Mach-O header is too large to relocate in '/Users/runner/work/syncplay/syncplay/dist/Syncplay.app/Contents/Resources/lib/python3.10/lib-dynload/cryptography/hazmat/bindings/_rust.so' (new size=2264, max size=2260, delta=72)
```
What can I do? Should I report this upstream?

**Comment by ronaldoussoren** [comment]
> @ronaldoussoren This just happened to me with `cryptography==38.0.3` (38.0.1 builds fine): https://github.com/Syncplay/syncplay/actions/runs/3401961428/jobs/5657407169
> 
> ```
> 
> ValueError: New Mach-O header is too large to relocate in '/Users/runner/work/syncplay/syncplay/dist/Syncplay.app/Contents/Resources/lib/python3.10/lib-dynload/cryptography/hazmat/bindings/_rust.so' (new size=2264, max size=2260, delta=72)
> 
> ```
> 
> What can I do? Should I report this upstream?

I haven't looked at cryptography in particular, but in general this can be fixed upstream bij adding ``-Wl, headerpad_max_install_names`` to the linker flags.  This will increase padding in the Mach-O headers.

**Comment by x3l51** [comment]
@ronaldoussoren 
> I haven't looked at cryptography in particular, but in general this can be fixed upstream bij adding `-Wl, headerpad_max_install_names` to the linker flags. This will increase padding in the Mach-O headers.

Can you elaborate on how to do this? I can't seem to find the right resource to apply this fix. I do have the exact same issue as @albertosottile 

Thanks!

**Comment by ronaldoussoren** [comment]
> @ronaldoussoren
> 
> > I haven't looked at cryptography in particular, but in general this can be fixed upstream bij adding `-Wl, headerpad_max_install_names` to the linker flags. This will increase padding in the Mach-O headers.
> 
> Can you elaborate on how to do this? I can't seem to find the right resource to apply this fix. I do have the exact same issue as @albertosottile
> 
> Thanks!

You, or however built the shared library that py2app complains about, need to add ``-Wl,-headerpad_max_install_names`` to the linker flags used to build that library.   Doing this will give py2app room to rewrite Mach-O load commands with paths that are longer than they are now. 

I don't know how to do this for cryptography in particular, that depends on their build tooling.

**Comment by x3l51** [comment]
Thank you for your response. I am no too versed into building from source with custom attributes but I've tried this (according to their [docs](https://cryptography.io/en/latest/installation/#building-cryptography-on-macos)):
```ZSH
pip uninstall cryptography -y
rm -rf ~/Library/Caches/pip
sudo port install openssl rust
env LDFLAGS="-L$(brew --prefix openssl@3)/lib -Wl -headerpad_max_install_names" CFLAGS="-I$(brew --prefix openssl@3)/include" pip install cryptography
rm -rf build dist && python3 setup.py py2app |& tee logs/build.log 
```
Which still returns me
```ZSH
ValueError: New Mach-O header is too large to relocate in 'myPath/dist/myApp.app/Contents/Resources/lib/python3.10/lib-dynload/cryptography/hazmat/bindings/_rust.so' (new size=2264, max size=2260, delta=72)
```
Can you point my in the right direction?
Do I understand this right that the issue here it the literal path length or those files?

Again: Thank you!

**Comment by albertosottile** [comment]
@x3l51 
I guess `pip install cryptography` still downloads the pre-built wheels from PyPI and does not re-build them locally. Also, you mixed the two types of instructions: you installed the dependencies with `port` but you are using the build command for `brew`. 
In short, I think you need to amend your build command as in:
```
env LDFLAGS="-L/opt/local/lib" CFLAGS="-I/opt/local/include" pip install --no-binary :all: cryptography
```
(I do not understand your comment about `excludes`, as it looks like your bundle can still function without `cryptography`...)

@ronaldoussoren I reported the issue upstream, to the best of my understanding of it: https://github.com/pyca/cryptography/issues/7847 . Please feel free to comment there to rephrase or clarify anything I wrote. Hope they listen.
