### ISSUE TITLE
Correctly packaging PyQt5's QtWebEngine

### ISSUE THREAD

**Issue by dliessi** [ronaldoussoren/py2app#280]
Please have a look at https://github.com/frescobaldi/frescobaldi/issues/1244.
The app bundle is produced by py2app, with the additional step of manually copying some plugins which are not included automatically and running macdeployqt to fix the app bundle (sorry for not reporting the problem earlier, I will open another issue for this).
Initially the problem was that QtWebEngineProcess was not found, although it was present in the application bundle inside the QtWebEngineCore framework.
After adding appropriate symlinks, it is found and the application does not crash, but nothing is displayed in the QtWebEngine window, with the following error:
```
dyld: Library not loaded: @executable_path/../Frameworks/QtGui.framework/Versions/5/QtGui
  Referenced from: [...]/test.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
```
In https://github.com/frescobaldi/frescobaldi/issues/1244#issuecomment-581360015 you can find minimal test files reproducing the problem.
Any help is very much appreciated.

**Comment by ronaldoussoren** [comment]
That's annoying.  I'm using the minimal test case in the frescobaldi issue you mention and can't even get the script to run without py2app:

```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```

This is with a fresh install of PyQt5:

```
$ pip list 
Package     Version Location                        
----------- ------- --------------------------------
altgraph    0.17    
macholib    1.14    
modulegraph 0.18    
pip         20.0.2  
py2app      0.20    /Users/ronald/Projects/gh/py2app
PyQt5       5.14.1  
PyQt5-sip   12.7.1  
setuptools  45.2.0  
```

All of this in a python 3.8.1 venv.

**Comment by ronaldoussoren** [comment]
Found what's cause of my repro failure: The web widgets are a separate PyPI package, see: https://www.riverbankcomputing.com/news/pyqt-512

**Comment by ronaldoussoren** [comment]
This is annoying, I cannot reproduce the problem...

```
from setuptools import setup
setup(
    app = ['main.py'],
    name = 'main',
    setup_requires = ['py2app'],
    script_args = ['py2app']
)
```

The file main.py contains the code from the GitHub issue mentioned earlier:

```
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl
app = QApplication( [] )
view = QWebEngineView()
view.load( QUrl( "http://www.frescobaldi.org" ) )
view.show()
app.exec_()
```

Running "python setup.py py2app" results in a application bundle "dist/main.app". Starting this from the command-line works file ("dist/main.app/Contents/MacOS/main"), as does opening the app bundle from the Finder.

**Comment by MAKOMO** [comment]
You can use any PyQt app like the following simple one:

`
import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QLabel, QGridLayout, QWidget
from PyQt5.QtCore import QSize

from PyQt5 import sip

class HelloWindow(QMainWindow):
    def __init__(self, parent = None):
        super(HelloWindow, self).__init__(parent)

        self.setMinimumSize(QSize(640, 480))
        self.setWindowTitle("Hello")

        title = QLabel("Hello World from PyQt", self) 
        title.setAlignment(QtCore.Qt.AlignCenter) 

        self.setCentralWidget(title)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWin = HelloWindow()
    mainWin.show()
    sys.exit(app.exec_())
`

Now if you put

`
	<key>NSRequiresAquaSystemAppearance</key>
	<string>false</string>
`

into the apps Info.plist to switch the automatic dark mode support of Qt on, the Window remains empty. Using PyQt 5.13.1 instead, the Window is displaying its content and the title bar shows the dark theme (if dark mode is turned on in macOS) as expected. With all PyQt versions later, like 5.13.2, 5.14.0 or 5.14.1 the window remains empty and the console prints that strange macOS error message.

**Comment by ronaldoussoren** [comment]
I can also build Frescobaldi, even after removing the block of code at "if args.standalone:" in macosx/mac-app.py and can open the lilipond documentation from the Help menu (I'm assuming this uses the Qt5 web browser widget).

**Comment by MAKOMO** [comment]
Could it be that this issue got resolved on the PyQt side begin of January.

https://www.riverbankcomputing.com/pipermail/pyqt/2020-January/042419.html

and the PyQt5 wheels got updated with this packaging fix?

https://www.riverbankcomputing.com/pipermail/pyqt/2020-January/042500.html

**Comment by ronaldoussoren** [comment]
Could be. I don't use PyQt myself anymore (I have used it in the past to build Windows GUIs, but not at this time).

**Comment by dliessi** [comment]
I have just upgraded to the latest version of PyQt and PyQtWebengine and I confirm the behaviour I described here and in the linked issue.

One difference between our systems is that I get the dependencies from MacPorts instead of PyPI.
In particular, PyQt is built from source on my machine.

**Comment by dliessi** [comment]
I installed PyQt with pip in a virtualenv and the example application bundle works as expected.
Probably an issue with how MacPorts builds PyQt.
Thanks for looking into it.

I will try building also Frescobaldi this way.
If it indeed works (I'll reopen this issue is it does not), it solves the problem, but only for macOS 10.13 and later, since that is the OS version PyPI's PyQt is built for (e.g. look for `LC_VERSION_MIN_MACOSX` in the output of `otool -l lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore`).
We still have users of previous OS versions, so I would like to make it work also with self-built or MacPorts-built PyQt.
