### ISSUE TITLE
Segmentation Fault with PyGobject "Getting Started" project

### ISSUE THREAD

**Issue by HarmoniousFunke** [ronaldoussoren/py2app#287]
Hello,

I tried to package the PyGobject Getting Started tutorial app and got a Segmentation Fault error.  I am using the Homebrew version of Python 3.7.7 in a virtual environment.

[Link to Getting Started Project](https://python-gtk-3-tutorial.readthedocs.io/en/latest/introduction.html)

This is what the error looks like calling the startup file directly:

```
MyMachine$ ./dist/simple_example.app/Contents/MacOS/simple_example
objc[56207]: Class GNotificationCenterDelegate is implemented in both /Users/Me/workspace/Archives/PyGObjectHello/dist/simple_example.app/Contents/Frameworks/libgio-2.0.0.dylib (0x104785948) and /usr/local/opt/glib/lib/libgio-2.0.0.dylib (0x105b9e948). One of the two will be used. Which one is undefined.
Segmentation fault: 11
```

First there is a warning about 'GNotificationCenterDelegate',  for now I am ignoring this.  Then there is the segmentation fault.

This is what the error looks like when launching the process in LLDB:

```
MyMachine$ lldb ./dist/simple_example.app/Contents/MacOS/simple_example 
(lldb) target create "./dist/simple_example.app/Contents/MacOS/simple_example"
Current executable set to './dist/simple_example.app/Contents/MacOS/simple_example' (x86_64).
(lldb) process launch
Process 56188 launched: '/Users/Me/workspace/Archives/PyGObjectHello/dist/simple_example.app/Contents/MacOS/simple_example' (x86_64)
objc[56188]: Class GNotificationCenterDelegate is implemented in both /Users/Me/workspace/Archives/PyGObjectHello/dist/simple_example.app/Contents/Frameworks/libgio-2.0.0.dylib (0x105157948) and /usr/local/opt/glib/lib/libgio-2.0.0.dylib (0x105c6a948). One of the two will be used. Which one is undefined.
Process 56188 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007fff65ce16f2 libsystem_platform.dylib`_platform_strlen + 18
libsystem_platform.dylib`_platform_strlen:
->  0x7fff65ce16f2 <+18>: pcmpeqb (%rdi), %xmm0
    0x7fff65ce16f6 <+22>: pmovmskb %xmm0, %esi
    0x7fff65ce16fa <+26>: andq   $0xf, %rcx
    0x7fff65ce16fe <+30>: orq    $-0x1, %rax
Target 0: (simple_example) stopped.
```

After recompiling the main.c file, I was able to narrow the problem to this line:

```
rval = py2app_PyRun_SimpleFile(mainScriptFile, c_mainScript); 
```
[[Direct Link](https://github.com/ronaldoussoren/py2app/blob/master/py2app/apptemplate/src/main.c#L1057)]

Anyway, I'm at the end of my mojo.  Any help would be appreciated.  Thanks!

**Comment by ronaldoussoren** [comment]
The error indicates that the app bundle is not yet standalone, but references files outside of the app bundle. Because of that one of the GObject/GTK libraries is loaded twice and that causes a segmentation fault (which doesn't surprise me).

The big question is why this happens, it might be that the gobject library contains a hardcoded reference to its installation prefix.

**Comment by ronaldoussoren** [comment]
See also #357.  As mentioned there py2app needs explicit support for GObject Introspection, and that's something I'll likely not work on because I don't use GTK myself and installing the library is non-trivial.
