### ISSUE TITLE
Python 3.6 + tkinter + py2app >= 0.14 broken?

### ISSUE THREAD

**Issue by LevN0** [ronaldoussoren/py2app#289]
Stumbling upon an error that was discussed on Stackoverflow, but I cannot find a bug report here.

https://stackoverflow.com/questions/45493029/valueerror-character-u6573552f-py2aap

<pre>
from setuptools import setup
OPTIONS = {}

setup(
    app = ['hello.py'],
    options = {
        'py2app': OPTIONS},
    setup_requires = ['py2app']
    )
</pre>

<pre>
from tkinter import *
from tkinter import messagebox

root = Tk()

def printworld():
    messagebox.showinfo('Hello', 'Hello World')

button1 = Button(root, text='Press me!', command=printworld)
button1.pack()

root.mainloop()
</pre>

The builds succeeds, but causes the following error on launch:

>ValueError: character U+6573552f is not in range [U+0000; U+10ffff]

Info:

py2app >= 0.14 (including 0.21)
Python 3.6.8 
OS X 10.11

Tried also Python 2.7 (did not have this issue) and Python 3.5 (did have this issue). I am using the Python.org installers.

**Comment by LevN0** [comment]
Copying apptemplate/prebuilt from v0.13 into same location for latest versions seems to workaround the issue. Probably breaks the fixes to the bootloaders made since then.

One of a5f8900eb254c5367c3abae62525a5c6c887d94d or a5f8900eb254c5367c3abae62525a5c6c887d94d must have broken this.

**Comment by ronaldoussoren** [comment]
This is fixed in the current release. Some code cleanup broke the app template.
