### ISSUE TITLE
py2app pygame python error 

### ISSUE THREAD

**Issue by newbiecoderplshelp** [ronaldoussoren/py2app#293]
im using py2app to convert my pygame script into an app. My app works fine when in alias but when i build a standalone app it causes an error and asks to terminate. when i go to dist > myapp show package contents > contents > macos > myapp it shows a long list and ends with this

ImportError: dlopen(/Users/macbook/Desktop/game/dist/jeosgame.app/Contents/Resources/lib/python3.8/lib-dynload/pygame/base.so, 2): Library not loaded: @loader_path/.dylibs/libSDL2-2.0.0.dylib
  Referenced from: /Users/macbook/Desktop/game/dist/jeosgame.app/Contents/Resources/lib/python3.8/lib-dynload/pygame/base.so
  Reason: image not found

does anyone know the fix to this? thanks

**Comment by ronaldoussoren** [comment]
This issue should be fixed in changes 2fde755a903bb9f20c3095b41f1ef4088f435690.

My current plan is to release a new version of py2app before the end of the year. Until then you can test by installing from the repository.
