### ISSUE TITLE
Support arm64 and Universal 2 

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#300]
Py2app needs some minor changes to support arm64 and "Universal 2" binaries

1. Make sure macholib works with arm64 binaries on macOS

2. Build the executable stubs with the right compiler flags (`-arch arm64 -arch x86_64`)

**Comment by hamishmb** [comment]
How do I specify this with the "arch" option? Regardless of what I try, I can't get arm64. Even "universal"  just gives PPC, i386, x86_64
