### ISSUE TITLE
Wheel package not available.

### ISSUE THREAD

**Issue by 2435191** [ronaldoussoren/py2app#304]
I made a very basic testing script for `py2app`. Here is the file `TestApplication.py`:
```
import rumps

class myApp(rumps.App):
    def __init__(self):
        super().__init__(title='myApp', name='myApp')
        self.menu = ['text', 'more text']

myApp().run()
```
And here is `setup.py`:
```
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import set
APP = ['TestApplication.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
```
When I run the command `python setup.py py2app -A` in Terminal, I get the following output:
```
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
running py2app
creating /Users/eab06/Desktop/WJB/PythonProjects/BoringButton/testapp/build
creating /Users/eab06/Desktop/WJB/PythonProjects/BoringButton/testapp/build/bdist.macosx-10.9-x86_64
creating /Users/eab06/Desktop/WJB/PythonProjects/BoringButton/testapp/build/bdist.macosx-10.9-x86_64/python3.7-standalone
creating /Users/eab06/Desktop/WJB/PythonProjects/BoringButton/testapp/build/bdist.macosx-10.9-x86_64/python3.7-standalone/app
creating /Users/eab06/Desktop/WJB/PythonProjects/BoringButton/testapp/build/bdist.macosx-10.9-x86_64/python3.7-standalone/app/collect
creating /Users/eab06/Desktop/WJB/PythonProjects/BoringButton/testapp/build/bdist.macosx-10.9-x86_64/python3.7-standalone/app/temp
creating /Users/eab06/Desktop/WJB/PythonProjects/BoringButton/testapp/dist
creating build/bdist.macosx-10.9-x86_64/python3.7-standalone/app/lib-dynload
creating build/bdist.macosx-10.9-x86_64/python3.7-standalone/app/Frameworks
*** creating application bundle: TestApplication ***
Copy '/Users/eab06/Desktop/WJB/PythonProjects/BoringButton/testapp/.eggs/py2app-0.21-py3.7.egg/py2app/apptemplate/prebuilt/main-x86_64' -> '/Users/eab06/Desktop/WJB/PythonProjects/BoringButton/testapp/dist/TestApplication.app/Contents/MacOS/TestApplication'
Done!
```
Then when I run `TestApplication.app`, I get a `TestApplication Error`.  I assume this has to do with the "missing wheels" messages at the start. How do I fix this?

**Comment by ronaldoussoren** [comment]
What error do you get if you start the application from the command line? That is, run "dist/TestApplication.app/Contents/MacOS/TestApplication" from the command-line. This should print a clearer error than just opening the app bundle.

What version of python and py2app do you use?

**Comment by ronaldoussoren** [comment]
The "wheel package unavailable" message is likely due to not having py2app installed, I get the same error when testing in a fresh virtual environment.  "setup_requires" can be a little too magic at times...

**Comment by Daud-stack** [comment]
:\Users\d\Desktop\management-system-13.0\venv\Scripts\python.exe C:/Users/d/Desktop/management-system-13.0/setup/mgmtsystem/setup.py
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
error in setup command: C:\Users\d\Desktop\management-system-13.0\setup\mgmtsystem\odoo\addons must contain exactly one installable Odoo addon dir, found []

Process finished with exit code 1

this Is what I get when I try running setup for the mgt system

**Comment by ronaldoussoren** [comment]
@Daud-stack : your appear to run python on a windows machine. Py2app does not support cross-building and must be run and installed on a macOS system.   Furthermore ensure that py2app is installed before running "python3 setup.py py2app".

**Comment by Daud-stack** [comment]
Noted thank you
