### ISSUE TITLE
Unknown Developer on other Mac OS system

### ISSUE THREAD

**Issue by MurlidharSingh** [ronaldoussoren/py2app#309]
I created a package and its working fine on my Mac, but when i send it to other MAC OS it is throwing the error unknown developer. Please help

**Comment by ronaldoussoren** [comment]
Hi,

The unknown developer popup is a security feature from macOS. There are two ways to deal with those:

1.  Become a paying customer of the Apple Developer Program and sign the application bundle after creating it with py2app. 
    
    This is something I want to add to py2app, but I haven't had time to do so.

2. On first launch open the application using the context menu ("right click"), you'll still get the warning but will also get an option to launch anyway.

    This is only necessary on first launch, after that the system has marked the application as verified (or rather, unmarks it as "unverified"). 

It is possible to disable this security feature, but that's something I wouldn't do. It should also be possible to avoid the warning by removing an extended attribute that tells the system this is a freshly downloaded application ("quarantined").

**Comment by MurlidharSingh** [comment]
> Hi,
> 
> The unknown developer popup is a security feature from macOS. There are two ways to deal with those:
> 
> 1. Become a paying customer of the Apple Developer Program and sign the application bundle after creating it with py2app.
>    This is something I want to add to py2app, but I haven't had time to do so.
> 2. On first launch open the application using the context menu ("right click"), you'll still get the warning but will also get an option to launch anyway.
>    This is only necessary on first launch, after that the system has marked the application as verified (or rather, unmarks it as "unverified").
> 
> It is possible to disable this security feature, but that's something I wouldn't do. It should also be possible to avoid the warning by removing an extended attribute that tells the system this is a freshly downloaded application ("quarantined").

**Comment by MurlidharSingh** [comment]
Hi @ronaldoussoren 
Thank you so much for creating this py2app, this is so helpful. Somehow i can't go for 2nd option which is restricted on our system by our system administrator

**Comment by ronaldoussoren** [comment]
Interesting.  I didn't know that is possible.

In that case you either need to sign the application (option 1), or remove the quarantine attribute on the second machine. This can be done from the command-line (see https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/). 

Another alternative is to distribute the application through a fileserver (and possibly something like a shared dropbox folder), that way the quarantine attribute is not added in the first place.

**Comment by MurlidharSingh** [comment]
Great Sir,

Thanks a ton!!

Would you mind explaining this more ---  Another alternative is to distribute the application through a fileserver (and possibly something like a shared dropbox folder), that way the quarantine attribute is not added in the first place.

**Comment by ronaldoussoren** [comment]
Current versions of macOS only give the warning about an unknown developer when starting an application that has the "quarantined" attribute I mentioned earlier. That's why you don't get the warning on your machine, but do get the warning on other machines when others download the application (website, mail, messaging tool, ...).

When you distribute the application through a file server of shared folder the quarantined attribute is not set, and hence the user won't get this warning.   The user doesn't have to run the application from the share, they can copy it to their machine (this is not seen as "downloading" by the system and hence will not result in setting the quarantine attribute).
