### ISSUE TITLE
py2app package contains dynamic loading files

### ISSUE THREAD

**Issue by rockmelodies** [ronaldoussoren/py2app#318]
The py2app package dynamically loads the project, but it can’t run normally. What should I do with this?

**Comment by rockmelodies** [comment]
I use importlib to dynamically load files, but after packaging, data cannot be returned

**Comment by ronaldoussoren** [comment]
py2app only includes python modules that it finds by analysing import statements.

The workaround is to include the modules you load using importlib manually. Relevant options:

* ``--include``: Include a particular python module
* ``--packages``: Include a complete package (including its data files)

The latter is probably the most relevant for your use case.

Please add a reproducer when that doesn't work.
