### ISSUE TITLE
Support univeral2 and M1

### ISSUE THREAD

**Issue by schriftgestalt** [ronaldoussoren/py2app#319]
Are there plans to support building universal (x86_64+arm64) apps? If so, how?

**Comment by ronaldoussoren** [comment]
The basic plan is that the end-user experience won't change, assuming you have a universal2 build of Python and the packages you need.  The latter is the largest problem right now, there is a universal2 installer for Python 3.9.1rc1 but no binary wheels for that variant (even for my own packages). 

I'm currently looking into why building universal2 wheels for PyObjC doesn't work. When that's done I can continue work on py2app (I need PyObjC for testing py2app).

**Comment by ronaldoussoren** [comment]
It looks like it will be fairly easy to support this.  On first glance the created app bundle will work fine when I sign the bundle (using an ad-hoc signature as described in https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes).

```
python -mmacholib find dist | xargs -n 1 codesign -s - --preserve-metadata=identifier,entitlements,flags,runtime -f  
```

Next up is to do this automatically.

Note that this does not require the use of a Developer ID.

**Comment by ronaldoussoren** [comment]
changeset 5e123a8b9586e3127a46f3945399586694ed7020 automatically signs bundles.

With this I can build a univeral2 build of examples/tkinter/hello_tk that actually works.

Current plan is to push out a release once I've done some more testing (which can take some time, the testsuite requires some hand holding).  With some luck the next release will be this weekend.

**Comment by schriftgestalt** [comment]
Any news on this: I have installed a universal python and when I try to build an app, I get this
```
error: [Errno 2] No such file or directory: b'/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app/bundletemplate/prebuilt/main-universal2'
```
I have tried installing py2app from pip and from sources.

**Comment by ronaldoussoren** [comment]
My current plan is to release before the new year. 

Building for M1 should work when you install py2app from the git repo, please let me know if it doesn't.

**Comment by ronaldoussoren** [comment]
Slightly later than expected, but py2app 0.23 is now on PyPI and fixes this issue.
