### ISSUE TITLE
wxPython 4.1.x bundles do not work (Catalina, Python 3.8 and 3.9)

### ISSUE THREAD

**Issue by hamishmb** [ronaldoussoren/py2app#321]
Hi,

I've been trying to re-bundle my program using wxPython 4.1.x. Unfortunately, it seems this does not work, even when using adapting the previous fixes (either of them) for wxPython 4.0 found at: https://github.com/ronaldoussoren/py2app/issues/252

The above fix fixes the "Image not found" error, but there is a new problem:

If launched outside the bunde, everything is fine, but when launched after bundling, my application's name appears in the menu bar and dock, but the menus never initialise and the program never opens. Tapping the icon on the dock also doesn't do anything.

I tried to reproduce this with your wxPython samples (doodle 2.4 and 2.5), but as they depend on cPickle, they no longer work as far as I can tell. Adjusting it to do:

`import pickle as cPickle`

Bypasses the error but the application just closes immediately before anything is displayed, bundled or not. The other samples also seem to have issues.

Any ideas what might cause this?

**Comment by hamishmb** [comment]
I tried building wxPython 4.0.7.post2 for Python 3.9 in an attempt to further verify that this issue isn't somehow related to Python 3.9, but was unsuccessful. It seems that that isn't a supported configuration.

However, I can confirm that I have this issue with both Python 3.8 and Python 3.9 with wxPython 4.1.1.

Hopefully that's enough to go off of, but if you need more information or debugging output or a minimal sample I'll be happy to provide those.

**Comment by ronaldoussoren** [comment]
A reproducer would be helpful, that makes it easier for me to debug the issue.

**Comment by ronaldoussoren** [comment]
Argv emulation was introduced to be able to write simple droplets: Apps that basically are a script that does something when you drop a file on their icon but don't present a GUI.  That option runs an event loop for a short while to intercept file-open and url-open events to add them to sys.argv, which might confuse GUI event loops started later.

For GUI applications its generally better to use the native support for reacting to file-open events (see <https://wiki.wxpython.org/Optimizing%20for%20Mac%20OS%20X> for how to to this for a version of wxPython).

That wiki might be why you have argv emulation on, the wiki has it in its example setup.py file for py2app.

**Comment by hamishmb** [comment]
Ah, that sounds like it's probably the issue. Running multiple event loops reminds me of issues I saw before where people were trying to run multiple GUI toolkits at once, with predictably bad results.

So I basically shouldn't be using argv emulation? By the sounds of it, I don't need it anyway so it's not a problem for me.

**Comment by ronaldoussoren** [comment]
That's correct, you shouldn't use argv emulation for GUI programs.

**Comment by hamishmb** [comment]
Okay, thanks :)
