### ISSUE TITLE
pip3

### ISSUE THREAD

**Issue by edwinm** [ronaldoussoren/py2app#329]
In the documentation I see "pip install py2app". I noticed "pip3 install py2app" also works.

Are there still major bugs in the Python 3 version of py2app?

If that's not the case, please update the documentation to use "pip3 install py2app".

**Comment by ronaldoussoren** [comment]
Good catch.

Py2app fully supports Python 3 (and has done so for a long time), and I expect that Python 2 support will slowly detoriate because I no longer use Python 2 myself.
