### ISSUE TITLE
pycryptodome on Raspberry

### ISSUE THREAD

**Issue by blitobyte** [ronaldoussoren/py2app#332]
Hello,

I've installed a flask app on a raspberry I had around. This app has been running on pythonanywhere.com for almost three years now, and also on other different computers. After a lot of trials, I had problems with pycrypto (only on the raspberry) and googling I came across pycryptodome.
I'm using Python 3.8 with pipenv. I've replaced pycrypto for pycryptodome (I've removed both folders: Crypto and pycryptpo).
Now I have this error:

[Tue Feb 02 13:11:09.535404 2021] [wsgi:error] [pid 5321:tid 1965982768] [remote 192.168.1.106:45600] OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-35m-arm-linux-gnueabihf.so': /home/pi/.local/share/virtualenvs/blisec-nYaGkmtR/lib/python3.8/site-packages/Crypto/Util/../Cipher/_raw_ecb.cpython-35m-arm-linux-gnueabihf.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.abi3.so': /home/pi/.local/share/virtualenvs/blisec-nYaGkmtR/lib/python3.8/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.so': /home/pi/.local/share/virtualenvs/blisec-nYaGkmtR/lib/python3.8/site-packages/Crypto/Util/../Cipher/_raw_ecb.so: cannot open shared object file: No such file or directory

This is my raspberry: Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

Any help or ideas? Need more information?

Thanks,

Pablo Sanz

**Comment by ronaldoussoren** [comment]
This is the repository of py2app, a tool to create macOS application bundles (".app").  I added support for pycryptodome to py2app, but am not a user of this library.

Please check with the pycryptodome project (https://www.pycryptodome.org/en/latest/)

**Comment by blitobyte** [comment]
Sorry, I thought you were the author of pycryptodome. So, no idea what the problem might be, right?

Your py2app works on linux? with flask apps?

**Comment by ronaldoussoren** [comment]
py2app does not work on linux. 

py2app is a tool for creating macOS application bundles on macOS.
