### ISSUE TITLE
py2app docs

### ISSUE THREAD

**Issue by hasii2011** [ronaldoussoren/py2app#333]
The link 

The most complete reference for the keys available to you is in[ Apple’s Runtime Configuration Guidelines](https://developer.apple.com/documentation/MacOSX/Conceptual/BPRuntimeConfig/index.html).

https://developer.apple.com/documentation/MacOSX/Conceptual/BPRuntimeConfig/index.html

on this page 

https://py2app.readthedocs.io/en/latest/tweaking.html

for the documentation is broken

**Comment by ronaldoussoren** [comment]
Thanks for the report. I've fixed the broken link.
