### ISSUE TITLE
setup.py is maybe missing some files for `apptemplate/prebuilt`?

### ISSUE THREAD

**Issue by mbutterick** [ronaldoussoren/py2app#334]
Hello, thank you for `py2app`. I am trying to bundle a script on an Apple M1. `python3` has been installed with `brew` and then `py2app` has been installed with `pip3` on a newly formatted machine.

The build fails with an error that a file `apptemplate/prebuilt/main-arm64` is missing. I notice that this file is [part of the source repo,](https://github.com/ronaldoussoren/py2app/tree/master/py2app/apptemplate/prebuilt) but it was not included in the files installed by `pip3`. When I copy it manually into the right place in `site-packages`, the build works.

On further inspection, I see that the `setup.py` [does not mention](https://github.com/ronaldoussoren/py2app/blob/84b93967ec044fb692c3ffee72d856df987ae26d/setup.py#L297-L331)`main-arm64` and other new app template files. I wonder if they were inadvertently omitted from this file, which is why the `pip3` install process is faulty.

**Comment by jhoyt4** [comment]
I am noticing the same issue in macports

`ls /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2app/apptemplate/prebuilt/
main-fat            main-i386           main-ppc            main-universal      secondary-fat       secondary-i386      secondary-ppc       secondary-universal
main-fat3           main-intel          main-ppc64          main-x86_64         secondary-fat3      secondary-intel     secondary-ppc64     secondary-x86_64`

Then files are missing in the wheel:
`% ls py2app-0.23-py2.py3-none-any.whl/py2app/apptemplate/prebuilt
main-fat            main-ppc            secondary-fat       secondary-ppc
main-fat3           main-ppc64          secondary-fat3      secondary-ppc64
main-i386           main-universal      secondary-i386      secondary-universal
main-intel          main-x86_64         secondary-intel     secondary-x86_64`

**Comment by kainjow** [comment]
@ronaldoussoren I'm seeing this issue too, with "main-universal2" binary missing from the wheel it appears.

**Comment by ronaldoussoren** [comment]
Good catch! I've just committed a fix for this an will push out a release today or tomorrow.

**Comment by jhoyt4** [comment]
@ronaldoussoren it appears you added the "main-universal2" pieces but did not add the arm pieces, am I missing something?

**Comment by ronaldoussoren** [comment]
You didn't mis anything. I've also added the arm64 binaries to the distribution archives.
