### ISSUE TITLE
argv_emulation=True hangs document-based wxPython programs on macOS until icon in Dock clicked manually

### ISSUE THREAD

**Issue by davidfstr** [ronaldoussoren/py2app#340]
Hi @ronaldoussoren thanks for working on py2app!

If I compile a Mac app with py2app with the argv_emulation=True (or 1) as per [one of the official wxPython wiki pages](https://wiki.wxpython.org/Optimizing%20for%20Mac%20OS%20X) then upon opening the app, it will fire the wx.App#OnPreInit event correctly but then hangs before it gets to wx.App#OnInit.

If you then click the app's icon in the Dock, the app gets unstuck and continues on to execute wx.App#OnInit and finishes starting up normally. (Another way of unblocking the app is to send an "activate" event to the application using AppleScript: `osascript -e "tell application "test" to activate"`.)

### Impact

This issue prevents supporting document-based applications on macOS that use wxPython and py2app, using wxPython's documented procedure for that (i.e. using argv_emulation=True with py2app). wxPython is a major development framework for GUI applications in Python on macOS.

Additionally this issue is a regression. See §"Regression" below.

### Full repro steps

* In Terminal, run:

```
$ python3 -m venv venv
$ source venv/bin/activate
$ pip3 install wxPython py2app
$ pip3 freeze
altgraph==0.17
macholib==1.14
modulegraph==0.18
numpy==1.20.1
Pillow==8.1.2
py2app==0.23
six==1.15.0
wxPython==4.1.1
$ python3 -V
Python 3.9.0
```

* Create a text file `test.py` with the contents:

```
# test.py
import os
import sys
import wx

sys.stdout = open(os.path.expanduser('~/Desktop/log.txt'), 'w', buffering=1)

class MyFrame(wx.Frame):
    """This window displays a Quit button."""
    
    def __init__(self, title = "Micro App"):
        wx.Frame.__init__(self, None , -1, title)
        btn = wx.Button(self, label = "Quit: argv[1:]=%r" % sys.argv[1:])
        btn.Bind(wx.EVT_BUTTON, self.OnQuit)
        self.Bind(wx.EVT_CLOSE, self.OnQuit)
    
    def OnQuit(self, event):
        self.Destroy()

class MyApp(wx.App):
    def OnPreInit(self):
        print('OnPreInit')
    
    def OnInit(self):
        print('OnInit#1')
        frame = MyFrame()
        frame.Show()
        print('OnInit#2')
        return True

app = MyApp(redirect=False)
app.MainLoop()
```

* Create a file `setup.py` with the contents:

```
# setup.py
from setuptools import setup

APP = ['test.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={
        'py2app': OPTIONS
    },
    setup_requires=['py2app'],
)
```

* Build and open the app:

```
$ rm -rf build dist ; python3 setup.py py2app
$ open dist/test.app/
```

* Notice that the app's main window does not appear.
* Click the app's icon in the Dock. Suddenly the app's main window appears!
    * Alternatively run in Terminal: `osascript -e "tell application "test" to activate"`

### Investigation

While the app is hung, if you open the `log.txt` file on the Desktop (which has the app's stdout stream), you'll notice that `OnPreInit` is printed but not the first `OnInit#1` item. So the app is getting hung between those lines.

Diving into the wxPython source code, I isolated the problem to interact with code somewhere in the following highlighted critical section: https://github.com/wxWidgets/Phoenix/blob/2d05ef594eb0354a93b1352a26a06bc0a43da6e2/src/app_ex.cpp#L251-L257

### Regression

The version of py2app exhibiting this bug is the latest as of this writing (py2app==0.23). I know that earlier versions of py2app did not have this problem. In particular the latest py2app as of Jan 24, 2012 (whatever it was) did not. A git bisect may therefore be able to isolate whatever changes in py2app are related to this issue.

### Potentially Related Issues

* https://github.com/ronaldoussoren/py2app/issues/155
* https://github.com/ronaldoussoren/py2app/issues/261#issuecomment-574367049

**Comment by davidfstr** [comment]
Tangentally related: How PyInstaller handles argv_emulation: https://github.com/pyinstaller/pyinstaller/pull/50 , which I thought was a good background read on how argv_emulation works in principle.

**Comment by davidfstr** [comment]
FWIW, I was able to alter my wxPython program to workaround the new inability to use argv_emulation=True: https://github.com/davidfstr/Crystal-Web-Archiver/commit/a57a0224e5ddbdcd910b908e8d3a7ded72d602da

**Comment by ronaldoussoren** [comment]
*argv_emulation* should not be used in combination with GUI toolkits.  On macOS most, if not all, of them should have an API to react to file-open events.

The *argv_emulation* feature starts a minimal event loop when the program is launching to intercept file-open events and insert them into ```sys.argv```.  That event loop is stopped before starting the actual script, but there might be unwanted interaction between the two loops.

**Comment by davidfstr** [comment]
> argv_emulation should not be used in combination with GUI toolkits. On macOS most, if not all, of them should have an API to react to file-open events.

Ah ha. So then suggested fixes seem to be:

* On py2app, revise any documentation related to argv_emulation to more clearly advertise that it should not be used with GUI toolkits like wxPython, QT, TKinter, etc. In particular the following pages:
    * https://py2app.readthedocs.io/en/latest/options.html?highlight=argv_emulation
    * https://py2app.readthedocs.io/en/latest/examples.html?highlight=argv_emulation
* On wxPython, revise any documentation related to argv_emulation in py2app to say it should not be used, and to provide alternatives.

I can take care of filing subissues on wxPython for the second bullet.

Would you like me to draft a PR for the first bullet, or would you prefer to take that?
