### ISSUE TITLE
PyZmq build behavior change with py2app version 0.24

### ISSUE THREAD

**Issue by mrclary** [ronaldoussoren/py2app#354]
With version py2app 0.22, pyzmq had the recipe that added zmq to the packages configuration which caused it to be installed outside the zip directory in the bundle. With 0.24, the autopackages looks like it is supposed to accomplish the same thing, but instead zmq is installed in the zip directory and also is missing some components, e.g. zmq.backends.cython.

Explicitly including zmq in the packages spec in my py2app setup puts it back outside the zip directory and is not missing any components, but I think this defeats the purpose of autopackages. What could be going wrong here?

I suspect that there may be similar issues with attempts to use automissing and autopackages in #352 and #353.

@ronaldoussoren , please advise.

**Comment by ronaldoussoren** [comment]
I'm debugging the issue, for some reason the autopackages recipe doesn't work properly.

**Comment by ronaldoussoren** [comment]
I've fixed the issue and intend to push out a release this weekend.
