### ISSUE TITLE
Autodetect ``__file__`` usage

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#368]
There are a number of python packages that won't work when included in site-packages.zip due to using file access based on ``__file__``. Check if it is possible to autodetect the usage of ``__file__`` when using ``modulegraph`` (this is a lot easier using ``modulegraph2``, but switching to that will be a lot of work).

**Comment by mrclary** [comment]
Also, any argument to `os.listdir`, `os.exists`, ... that resides in the bundled app zip directory will result in `[Errno 20] Not a directory: `.

**Comment by ronaldoussoren** [comment]
Both should only be a problem when the code tries to access resources by looking at a path related to the ``__file__`` attribute, which is a common pattern from before the introduction of ``importlib.resources`` and ``pkg_resources.get_resource_*`` (and still commonly used). 

Detection the use of a variable named ``__file__`` and then not including the package in the zip file should fix most of these without resorting to a recipe. That said, I haven't checked yet how easy it will be to add such a check in the current code base.

**Comment by ronaldoussoren** [comment]
So close, yet so far away...

Modulegraph already collects all global names that are set from code, but not those only read.  It is fairly easy to do something similar in py2app itself to find all global names that are read, but more work that I had hoped. I'm not adding this as a new feature to module graph at this point, that package is mostly frozen.

Basic idea for the recipe:

```
def check(cmd, mf):
    packages = set()
    for node in mf.flatten():
        if node.code is None:
            continue

        if node.identifier.startswith(os.path.dirname(os.path.dirname(__file__)) + "/"):
            # Skip py2app internals
            continue

        if "__file__" in scan_global_reads(node) and is_in_package(node):
            packages.add(package_name(node))

    if packages:
        return { "packages": packages }

    return None
```

I "just" have to fill in the blanks.

**Comment by ronaldoussoren** [comment]
Changeset 730df93d6ae58ac8662c847ee6985f4547bda0af implements the recipe.

I haven't changed the list of packages in the autopackages recipe yet, but at least some of them should be safe to remove.   

I did a quick check with botocore: Removing that from autopackages still results in botocore being included outside of site-packages.zip (as expected).   That said, I'm going to be conservative with autopackages and leave that as-is.
