### ISSUE TITLE
Qt6 Attribute Error

### ISSUE THREAD

**Issue by MAKOMO** [ronaldoussoren/py2app#376]
On updating my project from PyQt5 to PyQt6 I got the following error:

```
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app-0.26.1-py3.9.egg/py2app/recipes/qt6.py", line 22, in check
    qtdir = QLibraryInfo.location(QLibraryInfo.LibrariesPath)
AttributeError: type object 'QLibraryInfo' has no attribute 'location'
```

`QLibraryInfo.location` is deprecated since Qt6 and should be replaced by `QLibraryInfo.path`. Further, `Enum members must be fully qualified in PyQt6.` (PyQt Phil, https://www.riverbankcomputing.com/). 

Thus

```

QLibraryInfo.location(QLibraryInfo.LibrariesPath)
QLibraryInfo.location(QLibraryInfo.PluginsPath)
```

has to be replaced in `recipes/qt6.py` by

```
QLibraryInfo.path(QLibraryInfo.LibraryPath.LibrariesPath)
QLibraryInfo.path(QLibraryInfo.LibraryPath.PluginsPath)
```

Should have rather created a PR....

**Comment by ronaldoussoren** [comment]
Fixed by the PR.
