### ISSUE TITLE
How to support both PyQt5 and PyQt6

### ISSUE THREAD

**Issue by MAKOMO** [ronaldoussoren/py2app#377]
I have an app which I would like to transition from PyQt5 to PyQt6. I am using conditional imports like this

```
try:
    from PyQt6.QtCore import Qt
except Exception:
    from PyQt5.QtCore import Qt
```

That works fine on running from source. However, if I just have PyQt6 installed, py2app fails

```
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app-0.26.1-py3.9.egg/py2app/recipes/qt5.py", line 31, in check
    from PyQt5.QtCore import QLibraryInfo
ModuleNotFoundError: No module named 'PyQt5.QtCore'
```

I can successful build if both, PyQt5 and PyQt6 are installed, but in this case both are bundled. Is there a way around this?

**Comment by MAKOMO** [comment]
Worse, if I have both PyQt version installed, running from source I get

```
objc[94223]: Class QMacAutoReleasePoolTracker is implemented in both /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PyQt6/Qt6/lib/QtCore.framework/Versions/A/QtCore (0x10f54f2a8) and /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x134f26198). One of the two will be used. Which one is undefined.
```

Thanks for any hint,
Marko

**Comment by ronaldoussoren** [comment]
That's a bug in the Qt recipes, it should not fail the build when it cannot import PyQt.

The easiest workaround for now is to disable the recipe you don't want to use.  Either by editing the source or by monkey patching at runtime. To disable PyQt5 at runtime: ``from py2app.recipes import qt5; qt5.check = lambda cmd, mf: None``.

I'll probably push out a release with a fix during the weekend.

**Comment by MAKOMO** [comment]
Thanks Ronald for your quick reply. I will patch the source for now and look forward for your next release.

**Comment by ronaldoussoren** [comment]
Reopened the issue because I haven't fixed it yet.
