### ISSUE TITLE
SyntaxError: invalid or missing encoding declaration - py2app 0.26.1

### ISSUE THREAD

**Issue by am-fallah** [ronaldoussoren/py2app#382]
Hello
I use 
python 3.9.4(homebrew), py2app 0.26.1, and macOS Big Sur 11.6
and this is my setup file: 
```

from setuptools import setup

APP = ['tempo.py']
DATA_FILES = []
OPTIONS = {'packages': ['PyQt5', 'requests', 'time']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

```

app works well in alias mode but I got an error in terminal when I try to build it for deployment(Standalone)
and this is the error 
```
File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tokenize.py", line 335, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration
```

**Comment by ronaldoussoren** [comment]
I'm afraid I need a reproducer to be able to fix this.  The error suggests that there's an invalid encoding cookie in one of the source files (see https://www.python.org/dev/peps/pep-0263/).
