### ISSUE TITLE
Getting module error when I am using os.chdir

### ISSUE THREAD

**Issue by hsmatis** [ronaldoussoren/py2app#385]
I am getting the following error in py2app

 Files/read-pH-data.py", line 167, in <module>
    os.chdir(input_path)
NameError: name 'os' is not defined
2021-10-19 22:07:05.889 read-pH-data[71638:19898297] Launch error
2021-10-19 22:07:05.889 read-pH-data[71638:19898297] Launch error

I am unable to add the module
% pip3 install os
ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os

I tried installing modules chdir

my Pycharm code works

I am adding the modules to the Macintosh system Python3.  Before I received this error, I was required to install several other modules which worked.

**Comment by ronaldoussoren** [comment]
The error likely means that you're missing an ``import os`` statement at the start of the module using ``os.chdir``.
