### ISSUE TITLE
Launch Error on M1 pro

### ISSUE THREAD

**Issue by typemytype** [ronaldoussoren/py2app#397]
Hi

Ive got everything setup and installed with the latest pyobjc (8.1) and py2app (0.26.1).

A [simplified example](https://github.com/robotools/vanilla/tree/master/Demos/SimpleApp) works fine in alias mode. But with a [more complex app](https://github.com/typemytype/drawbot) I hit a `Launch Error`.

When running directly from `drawBot.app/Contents/MacOS/DrawBot` the app launches and works perfectly.

Is there a way to find what causes that Launch error? Console.app is not providing any use-full information.

![image](https://user-images.githubusercontent.com/1190358/150535674-009a234f-de9d-4028-af11-cc6974a14a58.png)

(in -A mode the app is not notarized nor codesigned) 

thanks!

**Comment by typemytype** [comment]
Found a solution by deleting all `.DS_Store` files in the .app bundle

**Comment by bensaine** [comment]
I have the exact same issue described yet no .DS_Store files are present
