### ISSUE TITLE
v0.24 and later are broken on Python 2.7

### ISSUE THREAD

**Issue by hamishmb** [ronaldoussoren/py2app#406]
Hi there,

I could have sworn I reported this already but apparently I forgot. Apologies if I did and this is a duplicate.

Recently when working on legacy versions of some projects I found that Python 2.7 isn't supported any more with 0.24 and later (gives a syntax error when bundling).

Considering 2.7 is now EOL, I guess this might be intentional, but in that case perhaps the PyPI information can be updated to show that Python 2.7 isn't supported any more?

Hamish

**Comment by ronaldoussoren** [comment]
I haven't intentionally dropped support for 2.7, but don't test with it either.

I'll see if I can push out a release that works on 2.7 again, and will change package metadata afterwards to ensure that pip notices that newer versions don't work with 2.7.

**Comment by hamishmb** [comment]
Cheers :)

**Comment by ronaldoussoren** [comment]
Version 0.28 should be compatible with python 2.7 again when it gets released. 

I'm leaving the issue open because I'll add a minimum python version to PKG-INFO after the release of 0.28 to ensure that python2.7 won't try to use a newer version.

**Comment by ronaldoussoren** [comment]
This is fixed in 0.28, and I've dropped support for Python 2 (and Python <= 3.5) in the main branch (which will be 0.29 later)
