### ISSUE TITLE
Bundling recent "black" fails

### ISSUE THREAD

**Issue by justvanrossum** [ronaldoussoren/py2app#476]
Running `python setup.py py2app` in the attached archived folder fails like this:

```
error: [Errno 2] No such file or directory: '/Users/just/code/git/drawbot/black_py2app/venv/lib/python3.9/site-packages/black-22.12.0.dist-info/top_level.txt'
```
This is happening since `black==22.10.0`

Here is a minimal reproducer:

[app_with_black.zip](https://github.com/ronaldoussoren/py2app/files/10277235/app_with_black.zip)

~Now, this may of course be a bug in black: https://github.com/psf/black/pull/3233#issuecomment-1361191055, but thought it good to report here, too.~

Cc @typemytype

**Comment by justvanrossum** [comment]
It seems that "top_level.txt" is not a required file, but is always added by setuptools. This is not the case with other packaging tools like Hatch (as used by Black).

**Comment by justvanrossum** [comment]
Info found here: https://blog.schuetze.link/2018/07/21/a-dive-into-packaging-native-python-extensions.html

> top_level.txt: Setuptools also add this file which contains only the name of your package. This is part of the (PEP-less) egg format, the predecessor of wheels, as described in [The Internal Structure of Python Eggs](https://setuptools.readthedocs.io/en/latest/deprecated/python_eggs.html). This file is not documented and not needed for wheels and therefore not added by other packagers such as poetry. (Interestingly enough, the [wheel repository](https://github.com/pypa/wheel), which adds the bdist_whl command to setuptools, does not even contain the string top_level.txt.)

**Comment by justvanrossum** [comment]
Ah, interesting! https://github.com/ronaldoussoren/py2app/commit/a1c0a2c33f953467d5abeb6447d2097e48dc3e30

**Comment by justvanrossum** [comment]
Maybe tangentially, running `black==22.8.0` from a bundled app fails like this:

```
Traceback (most recent call last):
  File "/Applications/DrawBot.app/Contents/Resources/DrawBot.py", line 66, in formatCode_
    self.vanillaWindowController.formatCode()
  File "/Applications/DrawBot.app/Contents/Resources/lib/python3.9/drawBot/ui/drawBotController.py", line 171, in formatCode
    import black
  File "src/black/__init__.py", line 32, in <module>
ModuleNotFoundError: No module named 'mypy_extensions'
```

Somehow black's dependencies aren't completely picked up by py2app.

**Comment by ronaldoussoren** [comment]
End of year vacation time for the win... Could you check if the head of the "v0.28-branch" branch fixes the issue for this?

Don't test the the master branch, that's fairly unstable at the moment and more importantly doesn't include the fix I pushed earlier.

**Comment by justvanrossum** [comment]
Fantastic, works like a charm with black 22.12.0. Thank you so much!

**Comment by ronaldoussoren** [comment]
Great, I'll push out a release later this week.

**Comment by typemytype** [comment]
thanks Ronald!

**Comment by ronaldoussoren** [comment]
a py2app with this fix was released yesterday.

**Comment by justvanrossum** [comment]
FWIW, while I see the release on PyPI, it is not listed on the GH releases page: https://github.com/ronaldoussoren/py2app/releases
