### ISSUE TITLE
the argument `know_paths` is missing in template for site.addsitedir

### ISSUE THREAD

**Issue by typemytype** [ronaldoussoren/py2app#489]
the py2app template: https://github.com/ronaldoussoren/py2app/blob/master/src/py2app/apptemplate/lib/site.py#L70

the default python implementation for [site.addsitedir]( https://docs.python.org/3/library/site.html#site.addsitedir) and [the source](https://github.com/python/cpython/blob/3.11/Lib/site.py#L207-L229)

Im receiving this error while pip installing inside an app:

```traceback
Traceback (most recent call last):
        File "site.pyc", line 182, in <module>
        File "/private/tmp/pip-build-env-jsosmj26/site/sitecustomize.py", line 8, in <module>
          site.addsitedir(path, known_paths=known_paths)
      TypeError: addsitedir() got an unexpected keyword argument 'known_paths'
```

thanks!

**Comment by colinmford** [comment]
Thanks, @typemytype!

I'm also having the same issue — it seems to come up most when asking pip to install from a git repo, i.e. `pip install git+https://github.com/joke2k/faker.git`

**Comment by typemytype** [comment]
Closing this issue, as this is not an py2app issue, sorry for the fuzz
